### ISSUE TITLE
bus1 tests - "INFO: suspicious RCU usage"

### ISSUE THREAD

**Issue by EduRam** [bus1/bus1#31]
Hi! 

bus1 outputs an OK to all tests!
But at the same time there is a kernel warning message:

[  130.167965] "INFO: suspicious RCU usage."
[  130.170209] 1 lock held by bus1-test/1475:
[  130.170401]  #0:  (bus1.active){++++.+}, at: [<ffffffffc0809e57>] bus1_fop_ioctl+0x57/0x1d0 [bus1]

Complete test log messages are on anexed file.

PS: I found a similiar complain on LKML, but with a different stack trace, on the subject: "[writeback] 8bc4ad9498: INFO: suspicious RCU usage. ]".

[bus1tests_on_vmguest.txt](https://github.com/bus1/bus1/files/457244/bus1tests_on_vmguest.txt)

**Comment by aalemayhu** [comment]
Hei,

I think I have seen this several times the last days. Attaching output as well
in case it is useful. Are you able to reproduce every time? It seems to happen
at random on my machine.

[log.txt](https://github.com/bus1/bus1/files/457310/log.txt)

**Comment by EduRam** [comment]
> Are you able to reproduce every time?

Yes.

**Comment by aalemayhu** [comment]
Have you tried to `git bisect`? Maybe this started to appear after some recent change. Assuming it is not a mainline thing.

**Comment by dvdhrm** [comment]
Fixed in -master with a revert. Thanks!
