### ISSUE TITLE
FTBFS with c-sundry 0~29

### ISSUE THREAD

**Issue by jengelh** [bus1/bus1#36]
With c-sundry 8deaceba08f06348c3825b2c99b4393e9e589bb9, bus1 no longer builds:

```
[   34s] In file included from src/message.c:14:0:
[   34s] src/message.h:15:9: error: unknown type name 'CRef'
[   34s]          CRef ref;
[   34s]          ^~~~
```

**Comment by dvdhrm** [comment]
This is not related to this repository. Please report it on the project you saw this on.

**Comment by jengelh** [comment]
No, this _is_ the right place. c-sundry changed their API, and bus1 is normally in need to be updated.

**Comment by Keruspe** [comment]
libbus1 is, bus1 isn't as it doesn't use CRef. Hence this is not the right
repository.
