### ISSUE TITLE
replace c with rust

### ISSUE THREAD

**Issue by sonicou** [bus1/bus1#37]
Before we build a new complex system software in a memory insecure language like C, which we know for sure will lead to hundreds of security issues even with the best guidelines in place, why not use a modern alternative like rust to avoid this kind of issue, leading to 95% less bugs and security issues with no effort.

**Comment by gregkh** [comment]
Given that the entirety of the rest of the Linux kernel is written in C, kernel modules need to remain as C code, sorry.

Feel free to work on porting Bus1 to a Rust-based operating system kernel, that would be an interesting project.

**Comment by sonicou** [comment]
There are already kernel modules written in rust https://github.com/tsgates/rust.ko
You can use Rust anywhere you can use C, and it can expose a C ABI, so that anything that can link to C code can link to it.

I don't see any reasen for this not to work.

**Comment by teg** [comment]
Sure, it would work, but we'd have no chance of getting this accepted upstream written in anything but C, so there is not really much point in discussing it.

If you want a fun project to try to port bus1 to rust to see how it would look like, I'd be interested in seeing it, but you should know that it would have virtually no chance of getting merged, so would only be an academic exercise.

**Comment by gregkh** [comment]
> I don't see a reason for this not to work

It wouldn't work, Rust doesn't run on all of the zillions of different processors that Linux runs on, and it would not be accepted at all by the upstream community, sorry.

**Comment by aep** [comment]
@sonicou 
The kernel module gotta be in C. It's already difficult enough to get it upstream D-:
But if you want a rust userspace, i'll happen quickly if bus1 becomes real.
