### ISSUE TITLE
test-io: test.h:102: test_open: Assertion `*mapp != ((void *) -1)' failed

### ISSUE THREAD

**Issue by aalemayhu** [bus1/bus1#54]
`test-io` fails when run on a Raspberry. Below is the full output of `make tt`:

    make[1]: Entering directory '/home/scanf/src/github.com/scanf/bus1/tools/testing/selftests/bus1'
    make[1]: Nothing to be done for 'all'.
    make[1]: Leaving directory '/home/scanf/src/github.com/scanf/bus1/tools/testing/selftests/bus1'
    make[1]: Entering directory '/home/scanf/src/tmp/linux-rpi-4.9.y'
      LD      /home/scanf/src/github.com/scanf/bus1/built-in.o
      LD      /home/scanf/src/github.com/scanf/bus1/ipc/bus1/built-in.o
      CC [M]  /home/scanf/src/github.com/scanf/bus1/ipc/bus1/handle.o
      CC [M]  /home/scanf/src/github.com/scanf/bus1/ipc/bus1/main.o
      CC [M]  /home/scanf/src/github.com/scanf/bus1/ipc/bus1/message.o
      CC [M]  /home/scanf/src/github.com/scanf/bus1/ipc/bus1/peer.o
      CC [M]  /home/scanf/src/github.com/scanf/bus1/ipc/bus1/tx.o
      CC [M]  /home/scanf/src/github.com/scanf/bus1/ipc/bus1/user.o
      CC [M]  /home/scanf/src/github.com/scanf/bus1/ipc/bus1/util.o
      CC [M]  /home/scanf/src/github.com/scanf/bus1/ipc/bus1/util/active.o
      CC [M]  /home/scanf/src/github.com/scanf/bus1/ipc/bus1/util/flist.o
      CC [M]  /home/scanf/src/github.com/scanf/bus1/ipc/bus1/util/pool.o
      CC [M]  /home/scanf/src/github.com/scanf/bus1/ipc/bus1/util/queue.o
      CC [M]  /home/scanf/src/github.com/scanf/bus1/ipc/bus1/tests.o
      LD [M]  /home/scanf/src/github.com/scanf/bus1/ipc/bus1/bus1.o
      Building modules, stage 2.
      MODPOST 1 modules
      CC      /home/scanf/src/github.com/scanf/bus1/ipc/bus1/bus1.mod.o
      LD [M]  /home/scanf/src/github.com/scanf/bus1/ipc/bus1/bus1.ko
    make[1]: Leaving directory '/home/scanf/src/tmp/linux-rpi-4.9.y'
    sudo sh -c 'dmesg -c > /dev/null'
    sudo sh -c 'rmmod bus1'
    sudo sh -c 'insmod ipc/bus1/bus1.ko'
    make[1]: Entering directory '/home/scanf/src/github.com/scanf/bus1/tools/testing/selftests/bus1'
    selftests: test-api [PASS]
    UDS took 6598 ns without payload
    UDS took 10542 ns
    test-io: test.h:102: test_open: Assertion `*mapp != ((void *) -1)' failed.
    Aborted
    selftests: test-io [FAIL]
    make[1]: Leaving directory '/home/scanf/src/github.com/scanf/bus1/tools/testing/selftests/bus1'
    [ 1654.992491] bus1: unloaded
    [ 1655.154023] bus1: run selftests..
    [ 1655.156364] bus1: loaded

I am not sure what is going wrong, but it looks like we can't allocate enough
memory. Applying the patch below fixes the issue and the tests pass.

    diff --git a/tools/testing/selftests/bus1/test.h b/tools/testing/selftests/bus1/test.h
    index fee815e1844d..c8591de6ebe0 100644
    --- a/tools/testing/selftests/bus1/test.h
    +++ b/tools/testing/selftests/bus1/test.h
    @@ -92,7 +92,7 @@ static inline int test_parse_argv(int argc, char **argv)
     
     static inline int test_open(const uint8_t **mapp, size_t *n_mapp)
     {
    -       const size_t size = 16UL * 1024UL * 1024UL;
    +       const size_t size = 16UL * 1024UL;
            int fd;
     
            fd = open(test_path, O_RDWR | O_CLOEXEC | O_NONBLOCK | O_NOCTTY);

**Comment by dvdhrm** [comment]
32bit machines don't have enough address space to run this test. Since we don't need large pools, reducing the mapping to 16kb should work fine. I'll have a look.

**Comment by aalemayhu** [comment]
@dvdhrm courtesy ping.

**Comment by dvdhrm** [comment]
Should be fixed in ad9014e073a0c86682f9fc322d19405b838f5b0f.

Thanks!
