### ISSUE TITLE
State/Status of project now that we have dbus-broker?

### ISSUE THREAD

**Issue by cdancy** [bus1/bus1#62]
Just wondering where you guys stand with pursing this project now that dbus-broker seems to solve a lot of problems the community has had with dbus. Maybe trojan horse this guy in at some later date?

**Comment by ERnsTL** [comment]
Greetings, as far as I know, an advantage of any form of "dbus in kernel" like `bus1` is to save on (expensive) CPU ring switches:

* dbus/dbus-broker in userspace: `program 1 -> kernel -> dbus in userspace -> kernel -> program 2` = 4 ring switches
* bus1 / "dbus in kernel" it goes `program 1 -> kernel -> program 2` = 2 ring switches.

The situation is even more grave in case of multicast to multiple programs.

That is something, where `dbus-broker` = a userspace implementation hits a glass ceiling.

**Comment by christinaa** [comment]
Yes, would also like to know what the state of the project is and whether there are still intentions to have it mainlined to finally have decent kernel-backed IPC similar to other modern operating systems instead of relying on domain sockets.

**Comment by cdancy** [comment]
Closing as no one seems to be responding

**Comment by vanillajonathan** [comment]
> Yes, would also like to know what the state of the project is and whether there are still intentions to have it mainlined to finally have decent kernel-backed IPC similar to other modern operating systems instead of relying on domain sockets.

Which operating systems have kernel-backed IPC? Which one(s) did you have in mind?
