### ISSUE TITLE
a peer context shared by two processes

### ISSUE THREAD

**Issue by oujunjun** [bus1/bus1#63]
Process B received the file descriptor from process A sent by UDS, and mmaped to it, thus process B has access to all nodes of the peer context that process A has created.

But seems that ioctl_recv drops all messages whether a message is destined to it or not, so it is not VERY possible for process B to send a message to process A that sharing the same peer context, suppose process B is receiving messages either.

From bus1 documentation there is a BUS1_RECV_FLAG_PEEK could ignore a message not destined to the node and it seems gone from the source.

I've write demo for testing above, It would be great if I made mistakes and I wish the processes could actually share the same peer context, or which is not actually necessary.

Thank you :)

**Comment by dvdhrm** [comment]
You should not be sharing bus1 contexts across applications. You should create one bus1 context per application.

The easiest way to bootstrap a bus1 communication is to create **2** bus1 contexts in a single application, then use BUS1_CMD_HANDLE_TRANSFER to create a node in the first context and import a handle into the second one. Optionally call it again in reverse order to create a back-channel as well.
Then fork your second process and pass **one** of the contexts to it, closing it in the parent. Now you have 2 processes with each one bus1 context.

**Comment by oujunjun** [comment]
So nodes cannot receive messages specified to him separately by sharing(mmaping to) the same context if a node cannot skip a message as receiving it(I guess you realized this before by BUS1_RECV_FLAG_PEEK), the way is to use a single recv && switch to dispense messages to different nodes, or, create a context for each node to receive its messages separately.

I thought and read from your documentation that a context can be shared freely by applications. "They are not bound to any process, but can be shared freely." and actually it does by sending file descriptors through UDS between processes, but only sharing the context without sharing the receiving queue, sometimes there is need for nodes belong to different process freely communicate with each other, without having to set up handles, because they are in one application and they are trusted in advance. 

I'm not quite sure about it, I feel like flexible( or esay ) if nodes can share(mmap to) the same recv queue and read messages separately likely in different processes belong to one application.

Thank you :)

**Comment by dvdhrm** [comment]
> So nodes cannot receive messages specified to him separately by sharing(mmaping to) the same context[.]

You **can** do this just fine. Technically, there is nothing preventing you from doing this.

> [If] a node cannot skip a message as receiving it (I guess you realized this before by BUS1_RECV_FLAG_PEEK), the way is to use a single recv && switch to dispense messages to different nodes, or, create a context for each node to receive its messages separately.

Just like on any other socket, when you call READ/RECV, you dequeue the data. Of course, you can use PEEK to avoid this, but this is not how any of those facilities are meant to be used.

If you **really, really** want to share a socket or bus1 context across processes, then you should also share some local structures like a local receive queue.

> I thought and read from your documentation that a context can be shared freely by applications. "They are not bound to any process, but can be shared freely."

You can share bus1 contexts freely. In most scenarios, this is not what you want, though.

> [And] actually it does by sending file descriptors through UDS between processes, but only sharing the context without sharing the receiving queue, sometimes there is need for nodes belong to different process freely communicate with each other, without having to set up handles, because they are in one application and they are trusted in advance.
> 
> I'm not quite sure about it, I feel like flexible( or esay ) if nodes can share(mmap to) the same recv queue and read messages separately likely in different processes belong to one application.

I cannot follow. What are you trying to achieve? Why would you want to share a node between processes? What is the problem of using a separate bus1 context in each process?

**Comment by oujunjun** [comment]
I'm just testing besides the test programs attached to the source code and have this question, thanks for your time and good advices.
