### ISSUE TITLE
[Question] Why handles are transitive?

### ISSUE THREAD

**Issue by ngortheone** [bus1/bus1#68]
Hey @dvdhrm 
The [website](https://bus1.org/bus1.html) explains that access rights can be passed transitively 

> However, access rights can be transmitted as auxiliary data with any message, effectively granting them to the receiver of the message. This even works transitively, that is, any peer that was granted access to an object can pass on those rights, even if they do not own the object. 

> Handles are local to each peer, but can be transmitted as auxiliary data with any message, effectively allocating a new handle to the same node in the destination peer. This works transitively, and each peer that holds a handle can pass it on further, or deliberately drop it. 

Can you elaborate why such design decision was made? What use-cases does this allow?

What about security implications? Here is an abstract example:
For example Peer Context 1(PC1) does not want to grant access to Peer1(P1), but it grants it to P2.
P2 shares the handle with P1, defeating security policy of PC1.

**Comment by dvdhrm** [comment]
The transitivity is crucial to capability based security systems. If you are interested in the details, a good start is the wikipedia page: https://en.wikipedia.org/wiki/Capability-based_security

In most cases `proxying` is a good counterargument for examples like you provided. That is, if PC1 does not want to grant access to P2, then P1 can still "proxy" the API for P2, and simply perform all operations on behalf of P2, thus effectively providing access to PC1 to P2. So even if the transitivity is not provided, P1 can "transitively" provide access to PC1.

Furthermore, note that you can always combine capability-based systems with mandatory-access-control (e.g., SELinux). This will allow you to enforce rules just as you described. Note that such rules are inherent to mandatory-access-control systems, but are not considered valid in capability-based systems.

**Comment by vinipsmaker** [comment]
Close question?
